name: ProjectGetCodeConfigSave

authors:
  - Asiya Shaji

type: SUITE

init:
 - CreateProjectopenAPISpecAbstract

endpoint: /projects/{{@CreateProjectopenAPISpecAbstract_Response.data.id}}/autocodeconfig

method: GET

auth: Default

headers:
- 'Content-Type: application/json'


assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"

cleanup:
  - DeleteProjectopenAPISpecAbstract

severity: Major

category: Functional

tags:
- V2
